# Generated by Django 5.1.4 on 2025-01-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=50)),
                ('datatype', models.CharField(max_length=50)),
                ('isActive', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_attribute',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('userName', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('birthDate', models.DateField(max_length=30)),
                ('contactNumber', models.CharField(default='', max_length=15)),
            ],
            options={
                'db_table': 'sos_employee',
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiativeName', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('startDate', models.DateField(max_length=25)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'sos_initiative',
            },
        ),
        migrations.DeleteModel(
            name='Marksheet',
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
